
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[359] =
    {   0,
        0,    0,   70,   67,   68,   67,   67,    1,   60,   67,
       67,   62,   58,   58,   67,   64,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,    0,   61,    0,   60,
       60,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   65,   62,   58,
       58,    0,   64,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   65,   58,   59,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   10,

       58,   58,   16,   63,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   49,    0,    0,    0,    0,
        0,    0,    0,    0,   66,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   11,   12,   58,   58,
       58,   17,    7,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   54,    0,    0,    0,
        0,   46,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   58,   58,   58,   58,   58,    6,    4,   58,   58,
       58,   58,   58,   13,   58,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   37,    0,   22,    0,

        0,    0,   55,    0,    0,   45,    0,    0,    0,    0,
       51,    0,   20,   18,   58,   58,   58,    2,    5,   58,
       58,   14,   15,    0,    0,    0,    0,   42,    0,   36,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       21,    0,    0,    0,    0,   58,   58,   58,   58,    8,
        9,    0,   28,    0,    0,    0,    0,    0,    0,    0,
       31,   27,    0,    0,   39,    0,    0,    0,    0,   29,
        0,    0,   26,   50,   58,   58,    0,   58,    0,    0,
       24,    0,    0,    0,    0,    0,    0,   25,    0,   23,
        0,   48,    0,    0,    0,    3,    0,    0,   56,   19,

       32,    0,    0,    0,    0,    0,   33,    0,    0,    0,
       53,    0,    0,    0,   57,    0,    0,    0,   41,    0,
        0,    0,    0,    0,    0,    0,    0,   43,    0,    0,
        0,    0,   30,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   52,   38,    0,    0,    0,   40,    0,    0,
       44,    0,    0,    0,   47,   34,   35,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    1,    1,    6,    6,
        6,    7,    1,    6,    8,    6,    9,   10,   11,   12,
       12,   12,   12,   12,   12,   12,   12,    6,   13,    1,
        6,    1,    1,    1,   14,   15,   15,   16,   17,   15,
       15,   15,   15,   15,   15,   18,   19,   15,   20,   15,
       15,   15,   15,   15,   21,   15,   15,   15,   15,   15,
        6,   22,    6,    1,   15,   23,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   15,   33,   34,   35,   36,
       37,   38,   15,   39,   40,   41,   42,   43,   44,   45,
       46,   15,    6,    1,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[47] =
    {   0,
        1,    2,    3,    1,    4,    1,    4,    1,    1,    4,
        4,    4,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[371] =
    {   0,
        0,    0,  523,  524,  524,  518,  514,  524,    0,   33,
       41,   42,  513,   44,    0,    0,   48,   49,   55,   56,
       52,   68,   69,   71,   72,   75,  515,  524,  511,    0,
        0,  499,  489,  473,  486,   45,  477,  484,   62,  474,
      482,   42,  467,   67,  477,  475,  499,    0,   93,  498,
       80,   95,    0,   74,   94,   99,  101,  102,   78,  108,
      110,  109,  113,  111,  114,  486,  476,  473,  467,  462,
      473,   84,  470,  472,  456,  468,  453,  462,  451,  457,
      455,  451,  460,  459,  479,  118,    0,  121,  524,  123,
      124,  125,  127,  128,  129,  130,  136,  133,  137,  154,

      139,  145,  478,  524,  145,  455,  152,  442,  448,  439,
      117,  442,  451,  437,  445,  436,  447,  436,  439,  435,
      434,  436,  443,  461,  524,  149,  152,  172,  144,  178,
      156,  179,  180,  147,  187,  185,  460,  459,  188,  191,
      193,  458,  457,  423,  426,  175,  433,  420,  418,  422,
      429,  178,  410,  413,  413,  414,  428,  416,  416,  417,
      412,  524,  408,  404,  403,  401,  404,  408,  413,  433,
      194,  199,  197,  198,  200,  201,  432,  431,  204,  202,
      206,  210,  211,  430,  216,  396,  395,  395,  394,  393,
      391,  402,  389,  387,  388,  387,  524,  398,  524,  383,

      387,  385,  524,  385,  380,  524,  378,  380,  389,  375,
      524,  381,  407,  406,  221,  219,  224,  405,  404,  222,
      229,  403,  402,  376,  366,  382,  364,  217,  372,  524,
      362,  362,  377,  359,  371,  361,  371,  369,  355,  353,
      524,  355,  367,  351,  356,  235,  228,  245,  237,  382,
      381,  357,  524,  351,  345,  344,  347,  350,  339,  350,
      524,  524,  344,  338,  524,  352,  348,  339,  333,  524,
      341,  330,  524,  524,  257,  243,  264,  246,  335,  342,
      524,  329,  330,  327,  325,  329,  336,  524,  323,  524,
      338,  524,  325,  331,  266,  352,  345,  270,  524,  350,

      524,  315,  323,  312,  312,  314,  524,  310,  243,  315,
      524,  320,  335,  279,  524,  319,  316,  304,  524,  302,
      315,  306,  299,  312,  311,  299,  301,  524,  295,  296,
      296,  292,  524,  293,  304,  290,  289,  284,  261,  261,
      258,  263,  524,  524,  262,  248,  246,  524,  261,  260,
      524,  243,  244,  242,  524,  524,  524,  524,  292,  270,
      253,  251,  296,  300,  304,  308,  312,  316,  320,  324
    } ;

static const flex_int16_t yy_def[371] =
    {   0,
      358,    1,  358,  358,  358,  359,  360,  358,  361,  358,
      358,  360,  362,  362,  363,  364,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  359,  358,  360,  361,
      361,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  365,  366,  360,  362,
      362,  363,  364,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  365,  367,  366,  362,  358,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  368,  358,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  368,
      367,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  362,  362,  362,  362,  362,
      362,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  362,  362,  369,  362,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  370,  362,  369,  369,  358,  362,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  370,  370,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,    0,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_nxt[571] =
    {   0,
        4,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       12,   12,    8,   13,   13,   13,   13,   13,   14,   13,
       13,   15,   16,   17,   13,   13,   18,   19,   13,   13,
       13,   20,   13,   13,   21,   13,   22,   23,   13,   24,
       25,   13,   13,   26,   13,   13,   32,   47,   30,   48,
       30,   49,   49,   49,   30,   30,   33,   34,   30,   35,
       36,   30,   30,   51,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   30,   30,   55,   30,   30,   70,
       30,   30,   78,   79,   30,   74,   30,   54,   58,   71,
       56,   57,   60,   75,   81,   88,   89,   89,   63,   30,

       30,   82,   49,   49,   49,   30,   64,   30,   30,   59,
       62,   65,   61,   90,   30,   30,   30,   30,   97,   30,
       30,  110,   91,  111,   86,   92,  125,   30,   96,   30,
       30,   30,   93,   30,   30,   30,   30,   94,   95,   30,
      100,  126,   30,   30,  156,   30,   98,   99,  101,  102,
       30,   30,  103,   30,  127,   30,  135,  157,   30,  129,
       30,  128,   30,  137,  138,  142,  172,  130,  144,  131,
      132,  133,  143,  134,  136,  148,  145,  139,   30,  149,
      175,  173,  146,  150,   30,   30,   30,  151,  180,  152,
      140,   30,  141,   30,   30,  174,  177,   30,  188,   30,

      171,  195,  125,   30,   30,   30,   30,   30,   30,  176,
       30,  189,   30,  179,  196,  213,   30,   30,  182,  178,
      185,  181,   30,  183,  217,   30,  216,   30,   30,  184,
       30,  218,  214,  220,   30,   30,  215,  222,  250,  251,
      256,   30,  219,   30,  246,  223,  277,  277,  257,   30,
      258,   30,   30,  259,   50,  221,   31,  248,  295,  295,
      247,  276,  249,   30,  278,  298,  298,  314,  314,  275,
      296,  298,  298,   29,  322,  357,  299,  356,  315,  323,
      314,  314,  299,  355,  300,  354,  353,  352,  351,  350,
      349,  315,   27,   27,   27,   27,   52,  348,  347,   52,

       53,   53,  346,   53,   85,   85,   85,   85,   87,   87,
      345,   87,  124,  124,  124,  124,  170,  170,  170,  170,
      297,  297,  297,  297,  313,  313,  313,  313,  344,  343,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  315,  325,  324,
      321,  320,  319,  318,  317,  316,   30,  299,   30,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,   30,   30,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,

      263,  262,  261,  260,  255,  254,  253,  252,   30,   30,
       30,   30,   30,   30,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,   30,   30,   30,  171,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  194,  193,  192,  191,
      190,  187,  186,   30,   30,   30,   30,  171,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      155,  154,  153,  147,   30,   86,  123,  122,  121,  120,
      119,  118,  117,  116,  115,  114,  113,  112,  109,  108,

      107,  106,  105,  104,   30,   86,   84,   83,   80,   77,
       76,   73,   72,   69,   68,   67,   66,   30,   28,   30,
       30,   28,  358,    3,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_chk[571] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   10,   11,   12,   11,
       14,   12,   12,   12,   17,   18,   10,   10,   21,   10,
       10,   19,   20,   14,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   22,   23,   18,   24,   25,   36,
       54,   26,   42,   42,   59,   39,   51,   17,   21,   36,
       19,   20,   23,   39,   44,   51,   52,   52,   26,   49,

       55,   44,   49,   49,   49,   56,   26,   57,   58,   22,
       25,   26,   24,   54,   60,   62,   61,   64,   59,   63,
       65,   72,   55,   72,   86,   56,   86,   88,   58,   90,
       91,   92,   57,   93,   94,   95,   96,   57,   57,   98,
       62,   88,   97,   99,  111,  101,   60,   61,   63,   64,
      129,  102,   65,  134,   90,  126,   98,  111,  127,   92,
      100,   91,  131,  100,  100,  101,  126,   93,  105,   94,
       95,   96,  102,   97,   99,  107,  105,  100,  128,  107,
      129,  127,  105,  107,  130,  132,  133,  107,  134,  107,
      100,  136,  100,  135,  139,  128,  131,  140,  146,  141,

      171,  152,  171,  173,  174,  172,  175,  176,  180,  130,
      179,  146,  181,  133,  152,  172,  182,  183,  136,  132,
      141,  135,  185,  139,  176,  216,  175,  215,  220,  140,
      217,  179,  173,  181,  247,  221,  174,  183,  221,  221,
      228,  246,  180,  249,  215,  185,  248,  248,  228,  276,
      228,  248,  278,  228,  362,  182,  361,  217,  275,  275,
      216,  247,  220,  275,  249,  277,  277,  295,  295,  246,
      276,  298,  298,  360,  309,  354,  277,  353,  295,  309,
      314,  314,  298,  352,  278,  350,  349,  347,  346,  345,
      342,  314,  359,  359,  359,  359,  363,  341,  340,  363,

      364,  364,  339,  364,  365,  365,  365,  365,  366,  366,
      338,  366,  367,  367,  367,  367,  368,  368,  368,  368,
      369,  369,  369,  369,  370,  370,  370,  370,  337,  336,
      335,  334,  332,  331,  330,  329,  327,  326,  325,  324,
      323,  322,  321,  320,  318,  317,  316,  313,  312,  310,
      308,  306,  305,  304,  303,  302,  300,  297,  296,  294,
      293,  291,  289,  287,  286,  285,  284,  283,  282,  280,
      279,  272,  271,  269,  268,  267,  266,  264,  263,  260,
      259,  258,  257,  256,  255,  254,  252,  251,  250,  245,
      244,  243,  242,  240,  239,  238,  237,  236,  235,  234,

      233,  232,  231,  229,  227,  226,  225,  224,  223,  222,
      219,  218,  214,  213,  212,  210,  209,  208,  207,  205,
      204,  202,  201,  200,  198,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  184,  178,  177,  170,
      169,  168,  167,  166,  165,  164,  163,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  151,  150,  149,  148,
      147,  145,  144,  143,  142,  138,  137,  124,  123,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
      110,  109,  108,  106,  103,   85,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   74,   73,   71,   70,

       69,   68,   67,   66,   50,   47,   46,   45,   43,   41,
       40,   38,   37,   35,   34,   33,   32,   29,   27,   13,
        7,    6,    3,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[70] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 
    0, 1, 0, 0, 0, 0, 1, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "veredit.l"
#line 2 "veredit.l"
// Copyright (C) 1999-2025  Erwin Waterlander
// Copyright (C) 1999       Ondrej Popp
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice in the documentation and/or other materials provided with
//    the distribution.
// 
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
// OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
// BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
// OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
// IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#define translation_unit_cc


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "std_macro.h"
#include "structures.h"
#include "error.h"
#include "text.h"
#include "nameset.h"
#include "file.h"
#include "veredit.h"

extern void setTranslation_unitParserInputStream(FILE* stream);
extern FILE * getTranslation_unitParserOutputStream(void);

expvar rwtext yyTOKEN_BUFFER = NULL;
static void lexReport(text token,
                      text val = NULL,
                      YYSTYPE* yys = NULL)
{
   TRACE(FILE *fo = getTranslation_unitParserOutputStream();)

   static size_t prev_size = 0;
   size_t need_size;

   if (val ne NULL)
      need_size = strlen(val) + strlen(token) + 6;
   else
      need_size = strlen(token) + 3;

   if (need_size > prev_size)
   {
      if (yyTOKEN_BUFFER eq NULL)
         yyTOKEN_BUFFER = (rwtext) malloc(sizeof(char) * need_size);
      else
         yyTOKEN_BUFFER = (rwtext) realloc((void *) yyTOKEN_BUFFER, sizeof(char) * need_size);

      prev_size = need_size;
   }

   if (val ne NULL)
   {
      sprintf(yyTOKEN_BUFFER, "'%s' (%s)", val, token);
      if (yys ne NULL)
         yys->text_field = textNew(val);
   }
   else
      sprintf(yyTOKEN_BUFFER, "'%s'", token);

   TRACE(fprintf(fo, "recognized %s\n", yyTOKEN_BUFFER);)
}
static void skip(text val)
{
   TRACE(FILE *fo = getTranslation_unitParserOutputStream();)

   TRACE(fprintf(fo, "skipping '%s'\n", val);)
}
#line 797 "lex.yy.c"
#line 798 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 96 "veredit.l"


#line 1016 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 359 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 524 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 98 "veredit.l"
{lexReport("char", (text) yytext); return yytext[0];}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 99 "veredit.l"
{lexReport("MODULE", (text) yytext); return MODULE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 100 "veredit.l"
{lexReport("ENDMODULE", (text) yytext); return ENDMODULE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 101 "veredit.l"
{lexReport("INPUT", (text) yytext); return INPUT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 102 "veredit.l"
{lexReport("OUTPUT", (text) yytext); return OUTPUT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "veredit.l"
{lexReport("INOUT", (text) yytext); return INOUT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 104 "veredit.l"
{lexReport("WIRE", (text) yytext); return WIRE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "veredit.l"
{lexReport("SUPPLY0", (text) yytext); return SUPPLY0;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 106 "veredit.l"
{lexReport("SUPPLY1", (text) yytext); return SUPPLY1;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 107 "veredit.l"
{lexReport("TRI", (text) yytext); return TRI;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 108 "veredit.l"
{lexReport("TRI0", (text) yytext); return TRI0;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 109 "veredit.l"
{lexReport("TRI1", (text) yytext); return TRI1;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 110 "veredit.l"
{lexReport("TRIOR", (text) yytext); return TRIOR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 111 "veredit.l"
{lexReport("TRIAND", (text) yytext); return TRIAND;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 112 "veredit.l"
{lexReport("TRIREG", (text) yytext); return TRIREG;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 113 "veredit.l"
{lexReport("WOR", (text) yytext); return WOR;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 114 "veredit.l"
{lexReport("WAND", (text) yytext); return WAND;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 115 "veredit.l"
{lexReport("ASSIGN", (text) yytext); return ASSIGN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 116 "veredit.l"
{lexReport("PARAMETER", (text) yytext); return PARAMETER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 117 "veredit.l"
{lexReport("E_MODULE", (text) yytext); return E_MODULE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 118 "veredit.l"
{lexReport("E_OUTPUT", (text) yytext); return E_OUTPUT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 119 "veredit.l"
{lexReport("E_INPUT", (text) yytext); return E_INPUT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 120 "veredit.l"
{lexReport("INSTANCE", (text) yytext); return INSTANCE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 121 "veredit.l"
{lexReport("ADDPORTS", (text) yytext); return ADDPORTS;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 122 "veredit.l"
{lexReport("DELPORTS", (text) yytext); return DELPORTS;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 123 "veredit.l"
{lexReport("RMPORTS", (text) yytext); return RMPORTS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 124 "veredit.l"
{lexReport("DELNETS", (text) yytext); return DELNETS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 125 "veredit.l"
{lexReport("ADDINST", (text) yytext); return ADDINST;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 126 "veredit.l"
{lexReport("MODINST", (text) yytext); return MODINST;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 127 "veredit.l"
{lexReport("KEEPMODNAME", (text) yytext); return KEEPMODNAME;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 128 "veredit.l"
{lexReport("DELINST", (text) yytext); return DELINST;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 129 "veredit.l"
{lexReport("ADDASSIGN", (text) yytext); return ADDASSIGN;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 130 "veredit.l"
{lexReport("DELASSIGN", (text) yytext); return DELASSIGN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 131 "veredit.l"
{lexReport("ADDPARAMETERDECL", (text) yytext); return ADDPARAMETERDECL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 132 "veredit.l"
{lexReport("DELPARAMETERDECL", (text) yytext); return DELPARAMETERDECL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 133 "veredit.l"
{lexReport("DELETE", (text) yytext); return DELETE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 134 "veredit.l"
{lexReport("EMPTY", (text) yytext); return EMPTY;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 135 "veredit.l"
{lexReport("BUFFEROUTPUTS", (text) yytext); return BUFFEROUTPUTS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 136 "veredit.l"
{lexReport("EXCLUDE", (text) yytext); return EXCLUDE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 137 "veredit.l"
{lexReport("REMOVEBUFFERS", (text) yytext); return REMOVEBUFFERS;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 138 "veredit.l"
{lexReport("BUFFERLIST", (text) yytext); return BUFFERLIST;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 139 "veredit.l"
{lexReport("BUFFER", (text) yytext); return BUFFER;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 140 "veredit.l"
{lexReport("BUFFERINPUT", (text) yytext); return BUFFERINPUT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 141 "veredit.l"
{lexReport("INSERTOBSINPUT", (text) yytext); return INSERTOBSINPUT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 142 "veredit.l"
{lexReport("OTHER", (text) yytext); return OTHER;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 143 "veredit.l"
{lexReport("NETS", (text) yytext); return NETS;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 144 "veredit.l"
{lexReport("INSERTOBSOUTPUT", (text) yytext); return INSERTOBSOUTPUT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 145 "veredit.l"
{lexReport("LISTINST", (text) yytext); return LISTINST;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 146 "veredit.l"
{lexReport("NET", (text) yytext); return NET;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 147 "veredit.l"
{lexReport("TIECELL", (text) yytext); return TIECELL;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 148 "veredit.l"
{lexReport("SHELL", (text) yytext); return SHELL;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 149 "veredit.l"
{lexReport("BUFASSIGNS", (text) yytext); return BUFASSIGNS;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 150 "veredit.l"
{lexReport("PULLUPPIN", (text) yytext); return PULLUPPIN;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 151 "veredit.l"
{lexReport("INST", (text) yytext); return INST;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 152 "veredit.l"
{lexReport("LABEL", (text) yytext); return LABEL;}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 153 "veredit.l"
{lexReport("INITIALSTAT", (text) yytext, &yylval); return INITIALSTAT;}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 154 "veredit.l"
{lexReport("DEFPARAM", (text) yytext, &yylval); return DEFPARAM;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 155 "veredit.l"
{lexReport("IDENTIFIER", (text) yytext, &yylval); return IDENTIFIER;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 156 "veredit.l"
{lexReport("IDENTIFIER", (text) yytext, &yylval); return IDENTIFIER;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 157 "veredit.l"
{lexReport("WILDCARDS", (text) yytext, &yylval); return WILDCARDS;}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 158 "veredit.l"
{lexReport("STRINGVALUE", (text) yytext, &yylval); return STRINGVALUE;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 159 "veredit.l"
{lexReport("INT_CONSTANT", (text) yytext); yylval.int_field = (int) strtol((text) yytext, NULL, 0); return INT_CONSTANT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 160 "veredit.l"
{lexReport("ALL", (text) yytext); return ALL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 161 "veredit.l"
{lexReport("compiler_directive", (text) yytext, &yylval); return compiler_directive;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 162 "veredit.l"
{skip((text) yytext);}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 163 "veredit.l"
{skip((text) yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 165 "veredit.l"
{skip((text) yytext);}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 166 "veredit.l"
{skip((text) yytext);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 168 "veredit.l"
ECHO;
	YY_BREAK
#line 1434 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 359 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 359 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 358);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 168 "veredit.l"


static YY_BUFFER_STATE BUFFER_STATE = NULL;
expfun void setTranslation_unitScannerToString(text string)
{
   extern text yyCURRENT_ITEM;

   yyCURRENT_ITEM = string;
   BUFFER_STATE = yy_scan_string(string);
}
expfun void setTranslation_unitScannerToStream(FILE* stream)
{
   extern FILE *yyin;
   extern text yyCURRENT_ITEM;

   setTranslation_unitParserInputStream(stream);

   yyin = stream;
   yyCURRENT_ITEM = "stream";
}
expfun void flushTranslation_unitScannerBuffer(void)
{
   YY_FLUSH_BUFFER;
}
#ifdef yywrap
#undef yywrap
#endif
expfun int yywrap(void)
{
   extern nameset yyITEMS;
   extern text yyCURRENT_ITEM;
   extern FILE *yyin;
   extern int yylineno;
   FILE *fo = getTranslation_unitParserOutputStream();

   while(isEmpty(yyITEMS) eq false)
   {
      yyCURRENT_ITEM = popFirst(yyITEMS);
      if (BUFFER_STATE ne NULL)
      {
         yy_delete_buffer(BUFFER_STATE);
         setTranslation_unitScannerToString(yyCURRENT_ITEM);
         yylineno = 1;
         return 0;
      }
      else if (yyin ne stdin)
      {
         Close(yyin);

         yyin = openR(yyCURRENT_ITEM, true);
         if (yyin ne NULL)
         {
            yylineno = 1;
            fprintf(fo, "- parsing '%s' ...\n", yyCURRENT_ITEM);
            return 0;
         }
      }
   }

   if (yyin ne stdin)
      Close(yyin);

   return 1;
}

